apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-vorting-app

spec:
  replicas: 1
  selector:
    matchLabels:
     name: result-app-pod
     app: demo-voting-app
  template:
    labels:
      name: result-app-pod
      app: demo-voting-app

    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80



